version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/merge-frontend

permissions:
  - object: scripts/deploy.sh
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mod: 755

hooks:
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: application_stop.sh
      timeout: 300
      runas: ubuntu
